version: "3"
services:
  hub:
    image: selenium/hub:4.1.0
  chrome:
    image: selenium/node-chrome:4.1.0
    shm_size: '2g'        
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:4.1.0
    shm_size: '2g'   
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub